### ISSUE TITLE
xwtorrents (Cardigann) not respecting "SeedBox Download Link" as False

### ISSUE THREAD

**Issue by Adthrawn** [Prowlarr/Prowlarr#1206]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have a tracker setup, Cardigann (xwtorrents). I had the setting "Use SeedBox Download Link" enabled for a time, but recently wanted to disable that to download locally. I unchecked the box, ran the sync between Prowlarr and Sonarr, tried to download a torrent, but it is downloading the Seedbox version.
![2022-11-21_11-09](https://user-images.githubusercontent.com/13037489/203103197-446d3ad3-866b-482b-ac58-7d71bc8b8cb9.png)

I also restarted both sonarr and prowlarr containers to see if that helped

### Expected Behavior

I would expect that disabling the option "Use SeedBox Download Link", that it would download the "regular" torrent file

### Environment

```markdown
- OS: Unraid 6.11.3
- Prowlarr: 0.4.8.2072
- Docker Install: Yes
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/Adthrawn/4a0f9ced610a9642b179eab37a03e134

[AB#4134](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4134)

**Comment by bakerboy448** [comment]
- Logs do not show any grab attempts nor capture any output for the field needed
- indexer response logging to have both of the responded download links and either the trace log of the grab to include the url, or the link copied for the grab from an in-prowlarr search to show what url prowlarr is using is likely needed.

```yml
    download_1:
      selector: a[href^="download.php"]
      attribute: href
    download_2:
      selector: a[href^="download2.php"]
      attribute: href
    download:
      text: "{{ if .Config.seedbox }}{{ .Result.download_2 }}{{ else }}{{ .Result.download_1 }}{{ end }}"
```
