### ISSUE TITLE
(Cardigann) "andmatch" filter doesn't do anything

### ISSUE THREAD

**Issue by mynameisbogdan** [Prowlarr/Prowlarr#1270]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Apparently the rows filter "andmatch" doesn't do anything.

Related lines:
https://github.com/Prowlarr/Prowlarr/blob/a58380031ddd39ee9f2a5ec1de51d94a0a9ffe6f/src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs#L643-L652

### Expected Behavior

To filter not matching rows. 

**[This change will affect all the definitions that use this filter.](https://github.com/Prowlarr/Indexers/search?q=andmatch)**

### Environment

```markdown
- OS: Unraid
- Prowlarr: 1.0.0.2171
- Docker Install: Y
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#4575](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4575)

**Comment by bakerboy448** [comment]
Yeah looks like it's missing the key match piece maybe?

Jackett's Cardigann docs

```YML
filters:
      # The andmatch filter will make sure that only torrents which contain all words from the search string are
      # returned. This is helpful if the tracker returns a lot of unrelated search results.
      - name: andmatch 
        # [OPTIONAL] argument, the maximum length of the search string which should be compared. Specify this if the
        # trackers cuts of the torrent name after a certain amount of characters.
        args: 66 
```

Jackett code

```csharp
case "andmatch":
                            var CharacterLimit = -1;
                            if (Filter.Args != null)
                                CharacterLimit = int.Parse(Filter.Args);

                            if (query.ImdbID != null && (TorznabCaps.MovieSearchImdbAvailable || TorznabCaps.TvSearchImdbAvailable))
                                break; // skip andmatch filter for imdb searches

                            if (query.TmdbID != null && (TorznabCaps.MovieSearchTmdbAvailable || TorznabCaps.TvSearchTmdbAvailable))
                                break; // skip andmatch filter for tmdb searches

                            if (query.TvdbID != null && TorznabCaps.TvSearchTvdbAvailable)
                                break; // skip andmatch filter for tvdb searches

                            var queryKeywords = variables[".Keywords"] as string;

                            if (!query.MatchQueryStringAND(release.Title, CharacterLimit, queryKeywords))
                            {
                                logger.Debug(string.Format("CardigannIndexer ({0}): skipping {1} (andmatch filter)", Id, release.Title));
                                SkipRelease = true;
                            }
                            break;
```
