### ISSUE TITLE
prowlarr cant connect to flaresolverr behind vpn

### ISSUE THREAD

**Issue by Dialgatrainer02** [Prowlarr/Prowlarr#2113]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

![image](https://github.com/Prowlarr/Prowlarr/assets/96637854/5781972f-f332-4a6d-b47e-09b62abb2f9b)
i have tried flaresolverr as hostname as well both fail

### Expected Behavior

connect to flaresolverr

### Steps To Reproduce

```yml
version: "3.9"
name: media-stack
services:

  # To use/enable VPN, Run this compose file with --profile: vpn. Its highly recommended to use VPN.
  vpn:
    ## Read https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers for details on configuring VPN for your service provider.
    profiles: ["vpn"]
    container_name: vpn
    image: qmcgaw/gluetun:v3.38.0
    cap_add:
      - NET_ADMIN
    environment:
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      VPN_PORT_FORWARDING: on
      VPN_PORT_FORWARDING_PROVIDER: protonvpn
      VPN_PORT_FORWARDING_STATUS_FILE: /gluetun/forwarded_port
      UPDATER_PERIOD: 24h
    ## Enable volume if VPN_SERVICE_PROVIDER: custom and VPN_TYPE: openvpn is used
    volumes:
    - "${DOCKER_DIR}/config/wireguard/wg0.conf:/gluetun/wireguard/wg0.conf"

    networks:
      - jellystack
    
    # Uncomment/enable below ports if VPN is used/enabled
    ports:
       # qbittorrent ports
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
       # prowlarr ports
      - 9696:9696
      #falresolverr ports
      - 8191:8191
    restart: "unless-stopped"

  ## Default credentials of qBittorrent - Username: admin password: adminadmin ##
  ## Change password after install from UI --> Tools --> Options --> WebUI ##
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:4.6.4

    # Unomment below if vpn is enabled
    depends_on:               # Uncomment this line if vpn is enabled
      - vpn                   # Uncomment this line if vpn is enabled

    # Comment below lines if VPN is enabled
    #networks:               # Comment this line if vpn is enabled
    #  - jellystack           # Comment this line if vpn is enabled

    # Unomment below line if vpn is enabled
    network_mode: service:vpn

    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
      WEBUI_PORT: 5080
    volumes:
      - ${DOCKER_DIR}/config/qbittorrent:/config
      - /opt/jellystack/downloads/:/downloads

    ## Comment/Disable below ports if VPN is enabled
#    ports:
#      - 5080:5080
#      - 6881:6881
#      - 6881:6881/udp
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.3.6
    networks:
    #  - jellystack   # Comment this line if VPN is enabled
    ## Uncomment below lines if VPN is enabled
      jellystack:
        ipv4_address: ${RADARR_STATIC_CONTAINER_IP} # It should be available IPv4 address in range of docker network `jellystack` e.g. 172.20.0.2
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    ports:
      - 7878:7878
    volumes:
      - ${DOCKER_DIR}/config/radarr:/config
      - /opt/jellystack/downloads/:/downloads
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:4.0.3
    container_name: sonarr
    networks:
   #   - jellystack   # Comment this line if VPN is enabled
    ## Uncomment below lines if VPN is enabled
      jellystack:
        ipv4_address: ${SONARR_STATIC_CONTAINER_IP} # It should be available IPv4 address in range of docker network `jellystack` e.g. 172.20.0.2
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
    volumes:
      - ${DOCKER_DIR}/config/sonarr:/config
      - /opt/jellystack/downloads/:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    depends_on:               # Uncomment this line if vpn is enabled
      - vpn                   # Uncomment this line if vpn is enabled
    network_mode: service:vpn
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    #ports:
    #  - "${PORT:-8191}:8191"
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.15.0

    # Uncomment below if vpn is enabled
    depends_on:               # Uncomment this line if vpn is enabled
      - vpn                   # Uncomment this line if vpn is enabled
    network_mode: service:vpn # Uncomment this line if vpn is enabled

    #networks:               # Comment this line if vpn is enabled
    #  - jellystack           # Comment this line if vpn is enabled
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
    volumes:
      - ${DOCKER_DIR}/config/prowlarr:/config

    # Comment below ports if VPN is enabled.
#    ports:
#      - 9696:9696
    restart: unless-stopped
  jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       networks:
         - jellystack
       environment:
          LOG_LEVEL: debug
          TZ: ${TZ}
       ports:
          - 5055:5055
       volumes:
          - ${DOCKER_DIR}/config/jellyseerr:/app/config
       restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:10.8.13
    container_name: jellyfin
    networks:
      - jellystack
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
    volumes:
      - ${DOCKER_DIR}/config/jellyfin:/config
      - /opt/jellystack/downloads/:/data
  # devices:
   #  - /dev/videoN:/dev/videoN # Mount GPU device 
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped
  
  # Doc: https://github.com/navilg/cleanmyarr
  # cleanmyarr:
  #   depends_on:
  #     - radarr
  #     - sonarr
  #   image: linuxshots/cleanmyarr:0.8.1
  #   container_name: cleanmyarr
  #   networks:
  #     - jellystack
  #   volumes:
  #     - cleanmyarr-config:/config
    # restart: unless-stopped
    # environment:
    # - CMA_MAINTENANCE_CYCLE: ${CMA_MAINTENANCE_CYCLE:-""}
    # - CMA_DELETE_AFTER_DAYS: ${CMA_DELETE_AFTER_DAYS:-""}
    # - CMA_ENABLE_EMAIL_NOTIFICATION: ${CMA_ENABLE_EMAIL_NOTIFICATION:-""}
    # - CMA_SMTP_USERNAME: ${CMA_SMTP_USERNAME:-""}
    # - CMA_SMTP_ENCODED_PASSWORD: ${CMA_SMTP_ENCODED_PASSWORD:-""}
    # - CMA_SMTP_TO_EMAILS: ${CMA_SMTP_TO_EMAILS:-""}
    # - CMA_ENABLE_GOTIFY_NOTIFICATION: ${CMA_ENABLE_GOTIFY_NOTIFICATION:-""}
    # - CMA_GOTIFY_URL: ${CMA_GOTIFY_URL:-""}
    # - CMA_GOTIFY_ENCODED_APP_TOKEN: ${CMA_GOTIFY_ENCODED_APP_TOKEN:-""}
    # - CMA_ENABLE_TELEGRAM_NOTIFICATION: ${CMA_ENABLE_TELEGRAM_NOTIFICATION:-""}
    # - CMA_TELEGRAM_ENCODED_BOT_TOKEN: ${CMA_TELEGRAM_ENCODED_BOT_TOKEN:-""}
    # - CMA_TELEGRAM_CHAT_ID: ${CMA_TELEGRAM_CHAT_ID:-""}
    # - CMA_MONITOR_RADARR: ${CMA_MONITOR_RADARR:-""}
    # - CMA_RADARR_URL: ${CMA_RADARR_URL:-""}
    # - CMA_ADARR_ENCODED_API_KEY: ${CMA_RADARR_ENCODED_API_KEY:-""}
    # - CMA_RADARR_ENABLE_NOTIFICATION: ${CMA_RADARR_ENABLE_NOTIFICATION:-""}


networks:
  jellystack:
    external: true
```
run this compose file and setup arrs and errs 
attempt to connect to flaresolverr 
get error

### Environment

```markdown
- OS: alpine vm in proxmox
- Prowlarr: 1.15
- Docker Install: 

Client:
 Version:           25.0.5
 API version:       1.44
 Go version:        go1.21.9
 Git commit:        d260a54c81efcc3f00fe67dee78c94b16c2f8692
 Built:             Mon Apr 15 17:53:43 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          25.0.5
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       e63daec8672d77ac0b2b5c262ef525c7cf17fd20
  Built:            Mon Apr 15 17:53:43 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.10
  GitCommit:        4e1fe7492b9df85914c389d1f15a3ceedbb280ac
 runc:
  Version:          1.1.12
  GitCommit:        51d5e94601ceffbbd85688df1c928ecccbfa4685
 docker-init:
  Version:          0.19.0
  GitCommit:        
```
- Using Reverse Proxy: not yet
- Browser: firefox
```


### What branch are you running?

Master

### Trace Logs?

https://pastebin.com/DxCTXj6V

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.
