### ISSUE TITLE
Prowlarr should respect X-Forwarded-Prefix

### ISSUE THREAD

**Issue by richard087** [Prowlarr/Prowlarr#2161]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Prowlarr does not respect X-Forwarded-Prefix so it cannot operate behind a path-based reverse proxy (as is often the case in k8s or similar environments).

### Describe the solution you'd like

Prowlarr (and all servarr apps) should reflect the X-Forwarded-Prefix in their generated URLs, as in https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer 

### Describe alternatives you've considered

- opening an additional port, specifically for prowlarr.
This is the solution I'm trying to move away from, and complicates networking and discovery, etc. It's a functional solution but the non-functional aspects are difficult and annoying.

### Anything else?

Example "recipe" (k8s template) for Open Media Vault demonstrates the issue. The /whoami path works well and shows the headers as they're re-written. When I open the prowlarr interface (e.g.: "http://hostname/prowlarr") with a web brower, I get a blank page. Inspection of the page shows that prowlarr is requesting to load assets (js, etc.) from the root (e.g.: "src=/index-d3d28c7a9fd39546fae8.js") which is not where the assets are served from.

```
# Prowlarr UI/API
# https://<FQDN>:8443/prowlarr

# whoami debug
# https://<FQDN>:8443/whoami
---
apiVersion: v1
kind: Namespace
metadata:
  name: servarr-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
  namespace: servarr-app
spec:
  ports:
  - name: prowlarr
    port: 9696
    targetPort: prowlarr
  selector:
    io.kompose.service: prowlarr
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: servarr-app
spec:
  ports:
  - name: whoami
    port: 80
    targetPort: web
  selector:
    app: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
  namespace: servarr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prowlarr
  template:
    metadata:
      labels:
        io.kompose.service: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: hotio/prowlarr:release
          ports:
          - containerPort: 9696
            name: prowlarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: servarr-app
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          imagePullPolicy: Always
          # Listen on port 8080 to run as non-root user
          args:
            - --port
            - '8080'
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            # Run the container as nobody:nogroup
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            limits:
              memory: '50Mi'
              cpu: '500m'
          ports:
            - name: web
              containerPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-stripprefix
  namespace: servarr-app
spec:
  stripPrefix:
    prefixes:
      - /whoami
      - /prowlarr
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: servarr-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/prowlarr`)
      kind: Rule
      middlewares:
        - name: test-stripprefix
          namespace: servarr-app
      services:
        - name: prowlarr
          port: 9696
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: servarr-app
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/whoami`)
      kind: Rule
      middlewares:
        - name: test-stripprefix
          namespace: servarr-app
      services:
        - name: whoami
          port: 80
---
```
