### ISSUE TITLE
Indexers - Jackett - C# Updates - Selector -> Selectors

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#298]
Note: not all; so we still need to support the ?legacy? selector

also some now have `downloadlink2` (fallback link)

Old:
```
download:
  # the .torrent url is on the on the details page
  selector: ul li a[href^="{{ .Config.downloadlink }}"]
  attribute: href
```
New:
```
download:
  # the .torrent URL and magnet URI are on the details page
  selectors:
    - selector: ul li a[href^="{{ .Config.downloadlink }}"]
      attribute: href
    - selector: ul li a[href^="{{ .Config.downloadlink2 }}"]
      attribute: href
```

relating to https://github.com/Prowlarr/Indexers/pull/3/files

[AB#1152](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1152)
