### ISSUE TITLE
[BUG]: IMDB tag search no longer works for TiK

### ISSUE THREAD

**Issue by hummingbirdy2** [Prowlarr/Prowlarr#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Any research with IMDB tag on TiK result in blank.

### Expected Behavior

Should list all related released

### Steps To Reproduce

1. On search, select `Cinematik` as Indexers
2. And search any present IMDB tag

### Environment

```markdown
- OS: Debian 10
- Prowlarr: 0.1.1.919
- Docker Install: Yes (Hotio)
- Using Reverse Proxy: No
```

### What branch are you running?

Nightly

### Anything else?

It's been working (2 months ago).
On TiK, to research with IMDB tag, `Detailed` research should be selected.

[AB#1555](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1555)

**Comment by bakerboy448** [comment]
Seems they don't even seem to support ID based search, only query? (That or Jackett does not/ has yet to? / cannot? support IMDb search for them

https://github.com/Prowlarr/Indexers/blob/8fbc7e75c66c38859c7b137417113de99f1dbed0/definitions/v1/cinematik.yml#L34

Logs?

what does a search on the site for imdb id look like?

May need an invite to this one

**Comment by garfield69** [comment]
possible fix https://github.com/Jackett/Jackett/commit/6dd1c0f187164ba3c28aedbb0229f757daa2c23a untested

**Comment by bakerboy448** [comment]
> possible fix [Jackett/Jackett@6dd1c0f](https://github.com/Jackett/Jackett/commit/6dd1c0f187164ba3c28aedbb0229f757daa2c23a) untested

Will be included in https://github.com/Prowlarr/Indexers/pull/36

later tonight

**Comment by bakerboy448** [comment]
> In my point of view. To fix the issue, we should force srchdtls to 1 in case of IMDB id search, so I try with that:

seems reasonable at a glance. Test it out, PR it for Jackett and when jackett merges it in, i'll pull it into that large PR that's building up

**Comment by garfield69** [comment]
the original
```yaml
    srchdtls: "{{ if .Config.srchdtls }}1{{ else }}0{{ end }}"
```
is a traditional `IF` in that it examines the value of the var and applies performs the true/false
https://github.com/Jackett/Jackett/wiki/Definition-format#if--else--end

I believe that the `IF OR` is not a true conditional for the values of the vars being true (contains 1) or false (contains 0), rather it operates on the var being null (the var is not defined or is empty, false) or  not-null (it contains a value, true)
https://github.com/Jackett/Jackett/wiki/Definition-format#if-orand--else--end

So perhaps try it with the conditional switched
```yaml
    srchdtls: "{{ if or .Query.IMDBID .Config.srchdtls }}1{{ else }}0{{ end }}"
```
and see if that works better

**Comment by garfield69** [comment]
although on reflection, I fully expect that  `&srchdtls=1` willalways be generated despite the setting of .Config.srchdtls as true or false
may need to remove the config option srchdtls altogether and use a regular IF for the .Query.IMDBID
since most sensible users are not going ot want to search descriptions regularly just titles, and we normally would only want to include descriptions for the imdbid searching.

**Comment by garfield69** [comment]
see https://github.com/Jackett/Jackett/commit/585b5359b562f978f88b887343716805875b2d99 for possible solution. Untested.

**Comment by bakerboy448** [comment]
> see [Jackett/Jackett@585b535](https://github.com/Jackett/Jackett/commit/585b5359b562f978f88b887343716805875b2d99) for possible solution. Untested.

added to the https://github.com/Prowlarr/Indexers/pull/36

@hummingbirdy2 give it a test - either in jackett or in prowlarr as a custom YML and let garfield know if it works!

Garfield - as always, appreciate the work on your end! :)

**Comment by hummingbirdy2** [comment]
Using your last commit @bakerboy448 in this research context:
![image](https://user-images.githubusercontent.com/71099752/132557175-02de326a-8190-4e0c-9aa9-32796eabd50f.png)

But `srchdtls` still set to `0`:
```log
|Info|NzbSearchService|Searching indexers: [Cinematik3] for {Term: tt1234567, Offset: 0, Limit: 0, Categories: []}
|Info|Cardigann|Adding request: https://www.cinematik.net/browse.php?search=tt1234567&incldead=1&srchdtls=0
```

There is any special syntax to set a query as IMDBID  ?

**Comment by bakerboy448** [comment]
> There is any special syntax to set a query as IMDBID ?

you cannot from the search page; that's just a boring text search

standard newznab / torznab endpoint query 

hit it with curl / the api docs (if accessible externally) / insomnia / etc.

**Comment by hummingbirdy2** [comment]
Tested with the API, and it's works well.
I test on a few search, and this next torznab values seems well parsed:
- `seeders`
- `files`
- `grabs`
- `peers`
- `downloadvolumefactor`
- `uploadvolumefactor`

But the definition is not perfect:
- The `Horror` category is missing into the [last yml definition](https://github.com/Prowlarr/Indexers/blob/c5ade11027a596dbd95a63e73992561712ab48fa/definitions/v1/cinematik.yml), how it should look:
```yml
caps:
  categorymappings:
    - {id: 1, cat: Movies, desc: "Comedy"}
    - {id: 4, cat: Movies, desc: "Action"}
    - {id: 5, cat: Movies, desc: "Horror"}
    - {id: 6, cat: Movies, desc: "Drama"}
    - {id: 7, cat: Movies, desc: "Documentary"}
    - {id: 9, cat: Movies, desc: "Crime"}
    - {id: 12, cat: Movies, desc: "Sci-Fi"}
    - {id: 17, cat: Movies, desc: "War"}
    - {id: 21, cat: Movies, desc: "Silent Films"}
    - {id: 23, cat: Movies, desc: "TV-Series"}
    - {id: 24, cat: Movies, desc: "Animation"}
    - {id: 25, cat: Movies, desc: "Exploitation"}
    - {id: 26, cat: Movies, desc: "Experimental"}
    - {id: 27, cat: Movies, desc: "Fantasy"}
    - {id: 29, cat: Movies, desc: "Short"}
    - {id: 30, cat: Movies, desc: "Western"}
    - {id: 32, cat: Movies, desc: "Foreign Languages"}
    - {id: 33, cat: Movies, desc: "Thriller"}
    - {id: 34, cat: Movies, desc: "Opera and Musical"}
```
- I don't know if it's possible, but it would better to use `cat=0` instead `c1=1&c4=1&c5=1&c6=1&c7=1&c9=1&c12=1&c17=1&c21=1&c23=1&c24=1&c25=1&c26=1&c27=1&c29=1&c30=1&c32=1&c33=1&c34=1` if we search through all category.

_Current situation:_
```text
https://www.cinematik.net/browse.php?c1=1&c4=1&c6=1&c7=1&c9=1&c12=1&c17=1&c21=1&c23=1&c24=1&c25=1&c26=1&c27=1&c29=1&c30=1&c32=1&c33=1&c34=1&search=tt1234567&incldead=1&srchdtls=1
```
_Proper situation:_
```text
https://www.cinematik.net/browse.php?cat=0&search=tt1234567&incldead=1&srchdtls=1
```
By doing this, if an another category are added, it would be possible to show his result too.

- Some other torznab value still unaccurate (`infohash`, `category`, `imdb`), but i lack knowledge in cardigan and web parsing in general to found the problem by my self.
I really want to help to polish the definition of this indexer, but I don't want to publish too much information in public area. There is an other way to share information to developers ?
